                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                           //mockup = vai mocapear os dados - "maquete modelo"
                                                                                                                                                                                                                                                                                           const usuarios = [
                                                                                                                                                                                                                                                                                            {id:1, nome:'Luiz', email:'luiz@email.com', senha:"admin"},
                                                                                                                                                                                                                                                                                            {id:2, nome:'Maria', email:'maria@email.com', senha:"admin"},
                                                                                                                                                                                                                                                                                            {id:3, nome:'Francine', email:'francine@email.com', senha:"admin"}
                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                        //buscar um usuario pelo seu id
                                                                                                                                                                                                                                                                                        function buscarUsuarioID(id) {
                                                                                                                                                                                                                                                                                            return usuarios.find(usuario => usuario.id == id);
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                        //função para buscar o id para esta fazendo a exclusão
                                                                                                                                                                                                                                                                                        function deletarUsuarioId(id) {
                                                                                                                                                                                                                                                                                            return usuarios.findIndex(user => user.id == id);
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                        function getUsuarios(){
                                                                                                                                                                                                                                                                                            return usuarios;
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                        export {buscarUsuarioID, deletarUsuarioId, getUsuarios}